services:
  database-mvc:
    image: postgres:17.0
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data-mvc:/var/lib/postgresql/data
      -
  database-rest:
    image: postgres:17.0
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data-rest:/var/lib/postgresql/data

  market-mvc:
    build:
      context: .
      dockerfile: market-mvc/Dockerfile
    image: market-mvc
    restart: always
    ports:
      - "${APP_HOST_PORT}:${APP_PORT}"
    depends_on:
      - database-mvc
      -
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    image: payment-service
    restart: always
    ports:
      - "${APP_HOST_PORT}:${APP_PORT}"
    depends_on:
      - database-rest
      -
volumes:
  db-data-mvc:
  db-data-rest: