services:
  redisserver:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: mypass
    command: [ "sh", "-c","exec redis-server --requirepass mypass" ]
    #command: redis-server --requirepass $$REDIS_PASSWORD
    networks:
      backend-net:
        aliases:
          - redisserver
volumes:
  db-data-mvc:
  db-data-rest:

networks:
  backend-net: