spring:
  application:
    name: my-market-app
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    contexts: prod
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/skeleton_repository
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50