server:
  port: ${APP_PORT_PAYMENT:8081}

spring:
  application:
    name: payment-service

  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment_repository}
    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST_PAYMENT:localhost}:${DB_PORT_PAYMENT:5432}/${DB_NAME_PAYMENT:payment_repository}
    username: ${DB_USER_PAYMENT:postgres}
    password: ${DB_PASS_PAYMENT:postgres}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      validation-query: SELECT 1


logging:
  level:
    root: WARN
    com.alex.payment: INFO
    com.alex.payment.service: DEBUG
    com.alex.payment.repository: INFO
    org.springframework.r2dbc: WARN
    org.springframework.transaction: INFO
  file:
    name: ${DIR_PAYMENT:/home/alexlakers/my-payment}/payment.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"