DELETE FROM orders_items;
DELETE FROM orders;
DELETE FROM items;

ALTER SEQUENCE IF EXISTS items_id_seq RESTART WITH 1000;
ALTER SEQUENCE IF EXISTS orders_id_seq RESTART WITH 1000;
ALTER SEQUENCE IF EXISTS orders_items_id_seq RESTART WITH 1000;
