-- schema.sql в src/main/resources
CREATE TABLE IF NOT EXISTS items(
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    title VARCHAR(128) NOT NULL,
                                    description VARCHAR(1024),
                                    img_path VARCHAR(128),
                                    price BIGINT NOT NULL,
                                    CONSTRAINT pk_items PRIMARY KEY (id),
                                    CONSTRAINT uq_items_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS orders(
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     total_sum BIGINT NOT NULL,
                                     CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders_items(
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           item_id BIGINT NOT NULL,
                                           order_id BIGINT NOT NULL,
                                           history_price BIGINT NOT NULL,
                                           count INT NOT NULL,
                                           CONSTRAINT fk_orders_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                                           CONSTRAINT fk_orders_items_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);